In [46]:
import numpy as np

In [47]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

In [48]:
print(arr.shape)

(2, 4)


In [49]:
print(arr.size)

8


In [50]:
print(arr.ndim)

2


In [51]:
arr = np.array([1,2,3,4], ndmin=3)

In [52]:
arr

array([[[1, 2, 3, 4]]])

In [53]:
print(arr.shape)

(1, 1, 4)


In [54]:
print(arr.ndim)

3


In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [56]:
arr.shape

(12,)

In [57]:
arr = arr.reshape(4, 3)

In [58]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
arr.ndim 

2

In [60]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [61]:
arr = arr.reshape(2,3,2)

In [62]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [63]:
arr.shape 

(2, 3, 2)

In [64]:
arr.ndim 

3

In [65]:
arr = np.array([1,2,3,4,5,6,7,8]) 

In [66]:
arr = arr.reshape(2,2, -1)

In [67]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [68]:
arr.shape

(2, 2, 2)

In [69]:
arr = np.array([[1,2,3,], [4,5,6]])

In [70]:
arr = arr.reshape(-1)

In [71]:
print(arr)

[1 2 3 4 5 6]


In [72]:
arr = np.array([[1,2,3], [4,5,6]])

In [73]:
arr = arr.flatten()

In [74]:
print(arr)

[1 2 3 4 5 6]


In [75]:
arr = np.array([1,2,3,4,5])
x = arr.copy()

In [76]:
arr[0] = 42

In [77]:
arr

array([42,  2,  3,  4,  5])

In [78]:
x 

array([1, 2, 3, 4, 5])

In [79]:
arr = np.array([1,2,3,4,5])
x = arr.view()

In [80]:
arr[0] = 42

In [81]:
arr

array([42,  2,  3,  4,  5])

In [82]:
x 

array([42,  2,  3,  4,  5])