In [49]:
import numpy as np

In [50]:
arr = np.array([1,2,3])

In [51]:
for x in arr:
    print(x)

1
2
3


In [52]:
arr = np.array([[1,2,3], [4,5,6]])

In [53]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [54]:
arr = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9], [10,11,12]]])

In [55]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [56]:
arr = np.array([[[1,2], [3,4], [5,6], [7,8]]])

In [57]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [58]:
arr = np.array([1,2,3])

In [59]:
for idx, x in np.ndenumerate(arr): # with index
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [60]:
arr = np.array([[1,2,3], [4,5,6]])

In [61]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [62]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [63]:
arr = np.concatenate((arr1, arr2))

In [64]:
print(arr)

[1 2 3 4 5 6]


In [65]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])

In [66]:
arr =np.concatenate ((arr1, arr2), axis=1)

In [67]:
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [68]:
arr.shape

(2, 4)

In [69]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [70]:
arr = np.stack((arr1, arr2))

In [71]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [72]:
arr.shape

(2, 3)

In [73]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [74]:
arr = np.hstack((arr1, arr2))

In [75]:
print(arr)

[1 2 3 4 5 6]


In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [77]:
arr = np.vstack((arr1, arr2))

In [78]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [80]:
arr = np.array_split(arr, 3)

In [81]:
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [82]:
arr = np.array([[1, 2], [3, 4], [5, 6], 
                [7, 8], [9, 10], [11, 12]])

In [83]:
arr = np.array_split(arr, 2)

In [84]:
arr

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [85]:
arr = np.array ([1, 2, 3, 4, 5, 4, 4])

In [86]:
x =  np.where(arr == 4)

In [87]:
print(x)

(array([3, 5, 6]),)


In [88]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [89]:
x = np.where(arr**2 == 4)

In [90]:
print(x)

(array([1]),)


In [91]:
arr = np.array([3, 2, 0, 1])

In [92]:
print(np.sort(arr))

[0 1 2 3]


In [93]:
arr = np.array(['pisang', 'melon', 'apel'])

In [94]:
print(np.sort(arr))

['apel' 'melon' 'pisang']


In [95]:
arr = np.array([[5,3,6], [7,2,9]])

In [96]:
print(np.sort(arr))

[[3 5 6]
 [2 7 9]]
