In [72]:
import numpy as np

In [73]:
arr = np.array([1, 2, 3, 4, 5])

In [74]:
print(arr)

[1 2 3 4 5]


In [75]:
print(type(arr))

<class 'numpy.ndarray'>


In [76]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

type(a), type(b)

(list, list)

In [77]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [78]:
arrayA = np.array(a)
arrayB = np.array(b)

type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [79]:
arrayA * arrayB
arrayA / arrayB

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [80]:
arrayA * 10

array([10, 20, 30, 40])

In [81]:
y_pred = np.array([1,0, 0, 1, 1, 0, 1, 1])
labels = np.array([0,1,0,1,1,0,1,1])

mse = (1/len(labels)) * np.sum(np.square(y_pred - labels))
print(mse)

0.25


In [82]:
arr = np.array(45)

In [83]:
print(arr)

45


In [84]:
arr = np.array([1,2,3,4,5])

In [85]:
print(arr)

[1 2 3 4 5]


In [86]:
arr = np.array(([1,2,3], 
                [4,5,6]))

In [87]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [88]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[6, 7, 8], [7, 8, 9]]])

In [89]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [7 8 9]]]


In [90]:
arr = np.zeros(5)

In [91]:
print(arr)

[0. 0. 0. 0. 0.]


In [92]:
arr = np.zeros((5, 2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [93]:
arr = np.ones((7,7))

In [94]:
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [95]:
arr = np.ones((3,4,2))

In [96]:
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [97]:
arr = np.array ([[1,2,3], [4,5,6], [7,8,9]])
arr = np.delete(arr, 1, axis=0)

In [98]:
arr = np.array ([[1,2,3], [4,5,6], [7,8,9]])
arr = np.delete(arr, 1, axis=0)

In [99]:
print(arr)

[[1 2 3]
 [7 8 9]]


In [100]:
del arr

In [101]:
arr = np.array([1,2,3,4])

In [102]:
arr[1: -1]

array([2, 3])

In [103]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [104]:
print(arr[1, 4])

10


In [105]:
print(arr[1, -1])

10


In [106]:
print(arr[1, 1:4])

[7 8 9]


In [107]:
arr = np.array([1,2,3,4])

In [108]:
print(arr.dtype)

int64


In [109]:
arr = np.array([1,2,3,4,], dtype='S')

In [110]:
print(arr)

[b'1' b'2' b'3' b'4']


In [111]:
arr = np.array([1,2,3,4,], dtype='I')

In [112]:
print(arr)

[1 2 3 4]


In [113]:
print(arr.dtype)

uint32


In [114]:
arr = np.array([1,2,3,4,], dtype=np.int32)

In [115]:
print(arr)

[1 2 3 4]


In [116]:
print(arr.dtype)

int32


In [117]:
arr = np.array([1.5,2.5,3.5])

In [118]:
arr

array([1.5, 2.5, 3.5])

In [119]:
arr = arr.astype('I')

In [120]:
arr

array([1, 2, 3], dtype=uint32)

In [121]:
print(arr.dtype)

uint32


In [122]:
arr = np.arange(15)

In [123]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [124]:
print(type(arr))

<class 'numpy.ndarray'>


In [125]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [126]:
arr = np.arange(10, 20)

In [127]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [128]:
arr = np.arange(10, 20, 2)

In [129]:
arr

array([10, 12, 14, 16, 18])

In [130]:
arr = np.arange(-1, 1, 0.1)
arr

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])