In [1]:
from numpy import random

In [2]:
x = random.randint(100)

In [3]:
x

48

In [4]:
x = random.rand()

In [5]:
x

0.17544579739561372

In [6]:
x = random.randint(100, size=(7))

In [7]:
x

array([20, 31, 50, 84, 26, 31, 89])

In [8]:
x = random.randint(100, size=(5, 9))

In [9]:
x

array([[36, 36, 89, 96, 51, 67, 52, 39, 86],
       [40, 29, 22, 64, 80, 74, 25, 77, 42],
       [47, 95,  8, 71, 59, 60,  4, 57, 59],
       [73, 91, 10, 76, 47, 65, 89,  9, 82],
       [25, 74, 66, 44, 26, 74, 11, 50, 57]])

In [10]:
x = random.rand(9)

In [11]:
x

array([0.05317512, 0.26692974, 0.12898011, 0.31879858, 0.630493  ,
       0.24797588, 0.82718463, 0.16392822, 0.74257996])

In [12]:
x = random.rand(5, 3)

In [13]:
x

array([[0.01321825, 0.01881443, 0.24344156],
       [0.11041173, 0.53254094, 0.68806971],
       [0.54130288, 0.55546097, 0.36245166],
       [0.53061502, 0.92350656, 0.57490285],
       [0.18671355, 0.49046958, 0.74897866]])

In [14]:
x = random.choice([3, 5, 7, 9])

In [15]:
x

5

In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [17]:
random.shuffle(arr)

In [18]:
print(arr)

[4 5 1 2 3]
