In [1]:
import numpy as np

In [2]:
arr = np.array([41, 42, 43, 44, 45])

In [3]:
x = ([True, False, True, False, True])

In [4]:
arr = arr[x]

In [5]:
print(arr)

[41 43 45]


In [6]:
arr = np.array([41, 42, 43, 44, 45])

In [7]:
filter_arr = arr > 42

In [8]:
filter_arr

array([False, False,  True,  True,  True])

In [9]:
arr = arr[filter_arr]

In [10]:
print(arr)

[43 44 45]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [12]:
filter_arr = arr % 2 == 0

In [13]:
arr = arr[filter_arr]

In [14]:
print(arr)

[2 4 6]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [16]:
filter_arr = (arr % 2 == 0) & (arr > 2)

In [17]:
arr = arr[filter_arr]

In [18]:
print(arr)

[4 6]


In [19]:
arr = np.array([['1', 'satu'],
              ['2', 'dua'],
              ['3', 'tiga'],
              ['4', 'empat'],
              ['5', 'lima']])

In [20]:
arr.shape

(5, 2)

In [21]:
filter_arr = np.array(['dua', 'tiga'])

In [22]:
arr = arr[np.in1d(arr[:, 1], filter_arr)]

In [23]:
arr

array([['2', 'dua'],
       ['3', 'tiga']], dtype='<U5')